stages:
  - deploy

pages:
  stage: deploy
  image: python:3.12.1-slim-bookworm
  before_script:
    - apt-get update && apt-get install make --no-install-recommends -y
    - python pip install -U sphinx
  script:
    - sphinx-build -b html ./public
    - cd docs && make html
    - mv docs/build/html ./public
  artifacts:
    paths:
      - public
  rules:
    if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH