image: python:3.12-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - python -m pip install sphinx
    - python -m pip install sphinx-rtd-theme
    - python -m pip install pdflatex

    - sphinx-build -b html docs/ public/
    - sphinx-build -b latex docs/ public/latex
    - cp public/latex/*.pdf docs/pdf
  artifacts:
    paths:
      - public
      - public/latex
  only:
    - main