image: python:3.12-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - python -m pip install sphinx
    - python -m pip install sphinx-rtd-theme
    - python -m pip install pdflatex
    - sphinx-build -b html docs/ public/
    - sphinx-build -b latex docs/ public/
  artifacts:
    paths:
      - public
  only:
    - main