image: python:3.12-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - python -m pip install sphinx
    - python -m pip install sphinx-rtd-theme
    - sphinx-build -b html docs/ public/
    - sphinx-build -b latex docs/ docs/latex
    - cd docs/latex && make
  artifacts:
    paths:
      - public
      - docs/latex/*.pdf
  only:
    - main
