image: python:3.12-alpine

stages:
  - deploy

pages:
  stage: deploy
  script:
    - python -m pip install sphinx
    - python -m pip install sphinx-rtd-theme
    - python -m pip install pdflatex

    - sphinx-build -b html docs/ _build/html
    - sphinx-build -M latex docs/ _build/
    - sphinx-build -M latexpdf . /_build/
    - cp _build/*.pdf docs/pdf/
  artifacts:
    paths:
      - _build/html/
      - _build
      - docs/pdf
  only:
    - main