image: python:3.9-slim
pages:
  stage: deploy
  script:
    - pip install -U sphinx
    - sphinx-build -b html .public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH