image: python:3.12

test:
  stage: test
  script:
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - sphinx-build -b html . public
  rules:
    - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH
    
pages:
  stage: deploy
  script:
  - pip install -U sphinx
  - pip install -U sphinx_rtd_theme
  - sphinx-build -b html . public
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH
